version: '3.1'

services:
  gameinitializer:
    build: "./GameInitializer"
    restart: "on-failure"
    expose:
      - "8080"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 5s
      timeout: 3s
      retries: 3

  fileio:
    build: "./FileIO"
    restart: "on-failure"
    expose:
      - "8080"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 5s
      timeout: 3s
      retries: 3

  main:
    build: "."
    restart: "on-failure"
    ports:
      - "8080:8080"
    depends_on:
      - gameinitializer
      - fileio
    environment:
      DISPLAY: unix$DISPLAY
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 5s
      timeout: 3s
      retries: 3