name: Push to Downstream

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push-downstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push to Downstream
      env:
        TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config --global user.email "github@actions.com"
        git config --global user.name "Github Action"
        git clone https://${TOKEN}:x-oauth-basic@github.com/roland-burke/ScotlandYardServer.git
        cd ScotlandYardServer
        echo "$(date)" > ./UPSTREAM.TXT
        git add ./UPSTREAM.TXT
        git commit -m "update from upstream"
        git push origin master
