name: Push to Downstream

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push-downstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push to Downstream
      run: |
        echo "Hello World"
        git help
